use serde::{Deserialize, Serialize};
use super::rpc_event::RPCEvent;

#[derive(Serialize, Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RPCCommand {
  Dispatch,
  Authorize,
  Authenticate,
  GetGuild,
  GetGuilds,
  GetChannel,
  GetChannels,
  CreateChannelInvite,
  GetRelationships,
  GetUser,
  Subscribe(RPCEvent),
  Unsubscribe,
  SetUserVoiceSettings,
  SelectVoiceChannel { channel_id: String },
  GetSelectedVoiceChannel,
  SelectTextChannel,
  GetVoiceSettings,
  SetVoiceSettings,
  CaptureShortcut,
  SetActivity,
  SendActivityJoinInvite,
  CloseActivityJoinReques,
  ActivityInviteUser,
  AcceptActivityInvite,
  InviteBrowser,
  DeepLink,
  ConnectionsCallback,
  BraintreePopupBridgeCallbac,
  GiftCodeBrowser,
  GuildTemplateBrowser,
  Overlay,
  BrowserHandoff,
  SetCertifiedDevices,
  GetImage,
  CreateLobby,
  UpdateLobby,
  DeleteLobby,
  UpdateLobbyMember,
  ConnectToLobby,
  DisconnectFromLobby,
  SendToLobby,
  SearchLobbies,
  ConnectToLobbyVoice,
  DisconnectFromLobbyVoic,
  SetOverlayLocked,
  OpenOverlayActivityInvit,
  OpenOverlayGuildInvite,
  OpenOverlayVoiceSetting,
  ValidateApplication,
  GetEntitlementTicket,
  GetApplicationTicket,
  StartPurchase,
  GetSkus,
  GetEntitlements,
  GetNetworkingConfig,
  NetworkingSystemMetrics,
  NetworkingPeerMetrics,
  NetworkingCreateToken,
  SetUserAchievement,
  GetUserAchievements,
}
